#!/bin/bash

if [[ ! -d ".git" ]]; then
    echo "No git repository"
else
    git add .
    if [[ -z $1 ]]; then
        m="Auto - Commit on $(date +"%c")
        $(git status -s)"
        else
        m=$1
    fi
    git commit -m "$m"
    git push
fi


