#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
else
  if [[ -z $1 ]]; then
    echo "Add your username when calling the function"
  else
    cu=$1

    curl https://raw.githubusercontent.com/3andan4/scripts_utils/master/repo --output repo

    chmod +x repo

    mv ./repo /usr/bin/repo

    echo 'for bcfile in ~/.bash_completion.d/* ; do
  . $bcfile
done' >/home/$cu/.bash_completion

    rm -rf /home/$cu/.bash_completion.d
    [[ ! -d /home/$cu/.bash_completion.d ]] && mkdir /home/$cu/.bash_completion.d

    echo 'repo_complete() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    words="renew update make help push -p version"

    COMPREPLY=( $(compgen -W "${words}" -- ${cur}) )
    return 0
}
complete -F repo_complete repo' >/home/$cu/.bash_completion.d/repo

    . /home/$cu/.bash_completion

    echo "Auto completion won't work on non-bash"
    echo "Reload your terminal"
    rm $0
  fi
fi
